### ISSUE TITLE
Can't install app because of private maven host

### ISSUE THREAD

**Issue by RenwaX23** [pinterest/slate#8]
Hey there 

While trying installing and running Slate I couldn't complete the Maven setup because inside the pom.xml this domain is used `https://mavenrepo-external.pinadmin.com` which I think is not accessible to public and only those with VPN or authorized IPs.

Could you please fix this or tell me a way to install the app 

Thanks

**Comment by ambud** [comment]
Hi @RenwaX23 we have fixed the issue, the UI build may fail on the M1 Mac

**Comment by RenwaX23** [comment]
Thanks it's fixed now but could you check this error I have when running run_slate.sh: 

```
java.lang.NoClassDefFoundError: Could not initialize class com.pinterest.slate.utils.HttpUtils
	at com.pinterest.slate.resources.ResourceFactory.init(ResourceFactory.java:63)
	at com.pinterest.slate.Slate.initV2(Slate.java:150)
	at com.pinterest.slate.Slate.run(Slate.java:118)
	at com.pinterest.slate.Slate.run(Slate.java:78)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.pinterest.slate.Slate.main(Slate.java:258)

```

Not sure if the problem is mine or its something else you confirm.

**Comment by ambud** [comment]
@RenwaX23 how are you launching it? are you using the latest scripts? I just pushed an update to the script to add defaults so it doesn't error out

**Comment by RenwaX23** [comment]
Thanks now I installed the app without any issues, but when visiting slate app there is this error which prevents the react app from running:

```
react-dom.production.min.js:216 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Wl (react-dom.production.min.js:280:177)
    at react-dom.production.min.js:149:163
    at Ia (react-dom.production.min.js:176:171)
    at Vs (react-dom.production.min.js:268:385)
    at Ol (react-dom.production.min.js:250:347)
    at Ml (react-dom.production.min.js:250:278)
    at Sl (react-dom.production.min.js:250:138)
    at vl (react-dom.production.min.js:243:163)
    at dl (react-dom.production.min.js:237:175)
    at Xl (react-dom.production.min.js:285:27)
ss @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
hi @ react-dom.production.min.js:131
hs @ react-dom.production.min.js:220
Ll @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Tl @ react-dom.production.min.js:252
vl @ react-dom.production.min.js:243
dl @ react-dom.production.min.js:237
Xl @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:289
yl @ react-dom.production.min.js:244
ru @ react-dom.production.min.js:289
t.render @ react-dom.production.min.js:296
(anonymous) @ index.js:12
(anonymous) @ serviceWorker.js:133
(anonymous) @ serviceWorker.js:133
react-dom.production.min.js:280 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Wl (react-dom.production.min.js:280:177)
    at react-dom.production.min.js:149:163
    at Ia (react-dom.production.min.js:176:171)
    at Vs (react-dom.production.min.js:268:385)
    at Ol (react-dom.production.min.js:250:347)
    at Ml (react-dom.production.min.js:250:278)
    at Sl (react-dom.production.min.js:250:138)
    at vl (react-dom.production.min.js:243:163)
    at dl (react-dom.production.min.js:237:175)
    at Xl (react-dom.production.min.js:285:27)
```

Also these website has been used which is not accessible to public:
https://analytics.pinadmin.com/ds/dashpin/v1/impression/dot/?toolId=138&itemType=209
https://statsboard.pinadmin.com/build2?settings=

**Comment by ambud** [comment]
We recently fixed this UI issue so it should no longer be happening, will need more details about your build / run environment to reproduce.

You can ignore the two URLs for now we will try to make them configurable in near future.

**Comment by RenwaX23** [comment]
I have everything as the same version in getting started page running on a Intel Macbook pro, the error is caused by react

**Comment by ambud** [comment]
Let me try to re-run on linux to see if the error persists.

**Comment by RenwaX23** [comment]
anything new?

**Comment by ambud** [comment]
Confirmed the bug still exists even in linux. 

@suryabhaskarkarri could you please double check that the fix for Tour is still present?

**Comment by ambud** [comment]
The issue should have been fixed now.

**Comment by RenwaX23** [comment]
Thanks works now
